### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by petr-tik** [cloudflarearchive/Cloudflare-CNAME-flattener#3]
Choose an appropriate license that outlines users' and contributors' rights to use and modify the script. 

Thanks

**Comment by xxdesmus** [comment]
This script is no longer needed since the release of https://blog.cloudflare.com/introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/

I think we can safely say this script falls under "do whatever you want with it" at this point. Is that correct @bundan ?

**Comment by bundan** [comment]
That's correct. The script uses an API endpoint that's pretty old anyway.

Jerome Chen
CloudFlare, Inc.
jerome@cloudflare.com
